# Generated by Django 3.0.8 on 2020-08-08 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_app', '0008_auto_20200808_2043'),
    ]

    operations = [
        migrations.CreateModel(
            name='teacher_content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.ImageField(upload_to='teacher_app')),
                ('subject', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='admin_app.subject_db')),
            ],
        ),
    ]
