# Generated by Django 3.0.8 on 2020-08-08 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher_content',
            name='topic',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='teacher_content',
            name='files',
            field=models.ImageField(blank=True, upload_to='teacher_app'),
        ),
    ]
