# Generated by Django 3.0.8 on 2020-08-08 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_app', '0004_remove_teacher_content_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='teacher_content',
        ),
    ]
