# Generated by Django 3.0.8 on 2020-08-08 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher_db',
            name='subject',
        ),
        migrations.AddField(
            model_name='teacher_db',
            name='subject',
            field=models.ManyToManyField(to='admin_app.subject_db'),
        ),
    ]
