# Generated by Django 3.0.8 on 2020-08-08 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_auto_20200808_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher_db',
            name='subject',
        ),
    ]
