# Generated by Django 3.0.8 on 2020-08-08 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0004_teacher_db_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=100)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.school_db')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.subject_db')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.Teacher_db')),
            ],
        ),
    ]
