# Generated by Django 3.0.8 on 2020-08-08 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0005_student_db'),
    ]

    operations = [
        migrations.CreateModel(
            name='content_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.ImageField(upload_to='admin_app')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.subject_db')),
            ],
        ),
    ]
