# Generated by Django 3.0.8 on 2020-08-08 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_app', '0006_content_db'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_db',
            name='email',
        ),
        migrations.RemoveField(
            model_name='teacher_db',
            name='email',
        ),
        migrations.AddField(
            model_name='student_db',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teacher_db',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
