# Generated by Django 3.0.8 on 2020-08-08 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0007_auto_20200808_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_db',
            name='username',
        ),
        migrations.RemoveField(
            model_name='teacher_db',
            name='username',
        ),
    ]
